//
//  StringMacro.h
//  plan
//
//  Created by Fengzy on 15/8/28.
//  Copyright (c) 2015年 Fengzy. All rights reserved.
//

#ifndef plan_StringMacro_h
#define plan_StringMacro_h

#define str_App_Title @"我有计划"
#define str_App_Slogan @"理想生活，我有计划"

#define str_Common_Tips1 @"请到“设置”-“隐私”-“照片”中找到”我有计划“，将按钮打开，允许访问相册"
#define str_Common_Tips2 @"请到“设置”-“隐私”-“相机”中找到”我有计划“，将按钮打开，允许使用摄像头"
#define str_Common_Tips3 @"至少写点什么吧"
#define str_Common_Tips4 @"已保存到手机相册"
#define str_Common_Tips5 @"图片加载失败"
#define str_Common_Tips6 @"暂无内容"
#define str_Common_Tips7 @"内容加载失败"

#define str_Common_Time1 @"刚刚"
#define str_Common_Time2 @"今天"
#define str_Common_Time3 @"昨天"
#define str_Common_Time4 @"一个月前"
#define str_Common_Time5 @"%ld分钟前"
#define str_Common_Time6 @"%ld小时前"
#define str_Common_Time7 @"%ld天前"
#define str_Common_Time8 @"%ld个月前"
#define str_Common_Time9 @"明天"

#define str_ViewTitle_1 @"我的"
#define str_ViewTitle_2 @"计划"
#define str_ViewTitle_3 @"任务"
#define str_ViewTitle_4 @"个人中心"
#define str_ViewTitle_5 @"岁月影像"
#define str_ViewTitle_6 @"常见问题"
#define str_ViewTitle_7 @"五星鼓励"
#define str_ViewTitle_8 @"建议反馈"
#define str_ViewTitle_9 @"关于我们"
#define str_ViewTitle_10 @"注册账号"
#define str_ViewTitle_11 @"找回密码"
#define str_ViewTitle_12 @"消息中心"
#define str_ViewTitle_13 @"消息详情"
#define str_ViewTitle_14 @"小区"
#define str_ViewTitle_15 @"修改密码"
#define str_ViewTitle_16 @"用户身份标识说明"
#define str_NickName @"昵称"
#define str_FirstView_1 @"假如你可以活到"
#define str_FirstView_2 @"岁"
#define str_FirstView_3 @"你仅剩"
#define str_FirstView_4 @"天"
#define str_FirstView_5 @"你的今天仅剩"
#define str_FirstView_6 @"秒"
#define str_FirstView_7 @"计划总数"
#define str_FirstView_8 @"已完成数"
#define str_FirstView_9 @"完成比例"
#define str_FirstView_10 @"类型"
#define str_FirstView_11 @"每日计划"
#define str_FirstView_12 @"长远计划"

#define str_Save_Success @"保存成功"
#define str_Save_Fail @"保存失败"
#define str_Modify_Success @"修改成功"
#define str_Delete_Success @"删除成功"
#define str_Delete_Fail @"删除失败"
#define str_Send_Success @"发送成功"
#define str_Send_Fail @"发送失败"
#define str_Report_Success @"举报成功"
#define str_Report_Fail @"举报失败"
#define str_Comment_Success @"评论成功"
#define str_Comment_Fail @"评论失败"
#define str_Register @"快速注册"
#define str_Register_Fail @"注册失败"
#define str_ForgotPassword @"忘记密码"
#define str_OK @"确定"
#define str_Cancel @"取消"
#define str_Show @"显示"
#define str_Refresh @"刷新"
#define str_Share @"分享"
#define str_Report @"举报"
#define str_Delete @"删除"
#define str_Comment @"评论"
#define str_Highlight @"精华"
#define str_Top @"置顶"
#define str_Author @"楼主"
#define str_Like @"赞"
#define str_Reply @"回复"
#define str_Save @"保存"
#define str_Notify_Later @"稍后提醒"
#define str_Delete_Plan @"删除该计划"
#define str_NoPlan_EveryDay @"暂无每日计划内容"
#define str_NoPlan_LongTerm @"暂无长远计划内容"
#define str_Alert_GetIt @"确定"
#define str_Plan_Add @"新增计划"
#define str_Plan_Edit @"编辑计划"
#define str_Plan_Tomorrow @"设为明天计划"

#define str_Photo_Add @"新增影像"
#define str_Photo_Edit @"编辑影像"
#define str_Photo_Add_Tips1 @"写点什么..."
#define str_Photo_Add_Tips2 @"请选择添加照片的方式"
#define str_Photo_Add_Tips3 @"请选择照片"
#define str_Photo_Add_Tips4 @"可选9张照片"
#define str_Photo_Add_Tips5 @"至少留一张照片吧~"
#define str_Photo_Add_Tips6 @"已选%ld张/还可选%ld张照片"
#define str_Photo_Add_Tips7 @"拍照地点"
#define str_Photo_Tips1 @"暂无影像内容"
#define str_Photo_Detail @"影像详情"
#define str_Photo_Age @"岁"
#define str_Photo_Location @"地点："
#define str_Photo_Date @"时间："
#define str_Photo_Detail_Tips1 @"时间：%@"
#define str_Photo_Detail_Tips2 @"%@   地点：%@"
#define str_Photo_Delete_Tips @"删除该影像"

#define str_Task_Add @"新建任务"
#define str_Task_Edit @"编辑任务"
#define str_Task_Detail @"任务详情"
#define str_Task_AddRecord @"点我"
#define str_Task_Tips1 @"暂无任务内容"
#define str_Task_Delete_Tips @"删除该任务"

#define str_Posts_Add @"发帖"
#define str_Posts_Delete @"删除帖子"
#define str_Posts_Add_Tips1 @"可选2张照片"
#define str_Posts_Add_Tips2 @"至少写点什么或留一张照片吧~"

#define str_PostsList_Tips1 @"网络罢工啦，点击重试~"
#define str_PostsList_Tips2 @"如果确定，将删除该帖子"
#define str_PostsDetail_Comment_Tips1 @"评论一下"
#define str_PostsDetail_Comment_Tips2 @"暂无评论，快占沙发~"

#define str_PersonalCenter_Tips1 @"你的恒心超过了"
#define str_PersonalCenter_Tips2 @"的坚持者"
#define str_PersonalCenter_SubTitle1 @"最近连续签到天数"
#define str_PersonalCenter_SubTitle2 @"最大连续签到天数"
#define str_PersonalCenter_SubTitle3 @"每日计划总数"
#define str_PersonalCenter_SubTitle4 @"每日计划完成总数"
#define str_PersonalCenter_SubTitle5 @"长远计划总数"
#define str_PersonalCenter_SubTitle6 @"长远计划完成总数"
#define str_PersonalCenter_SubTitle7 @"任务总数"
#define str_PersonalCenter_SubTitle8 @"影像总数"

#define str_More @"更多"
#define str_More_Settings @"通用设置"
#define str_More_Welcome @"去欢迎页"

#define str_More_Feedback_Tips1 @"当前系统版本不支持应用内发送邮件功能"
#define str_More_Feedback_Tips2 @"你还没有设置邮件账户"
#define str_More_Feedback_Tips3 @"请输入你的建议或反馈~"
#define str_More_Feedback_Tips4 @"取消编辑邮件"
#define str_More_Feedback_Tips5 @"保存邮件成功"
#define str_More_Feedback_Tips6 @"发送邮件成功"
#define str_More_Feedback_Tips7 @"保存或者发送邮件失败"
#define str_More_Feedback_Tips8 @"我有计划 For iOS"

#define str_Settings_Acount @"账号："
#define str_Settings_Avatar @"头像："
#define str_Settings_Nickname @"昵称："
#define str_Settings_Nickname_Tips @"点击修改昵称"
#define str_Settings_Gender @"性别："
#define str_Settings_Gender_M @" 男"
#define str_Settings_Gender_F @" 女"
#define str_Settings_Birthday @"生日："
#define str_Settings_Birthday_Tips @"点击设置生日"
#define str_Settings_Lifespan @"生命："
#define str_Settings_Lifespan_Tips @"点击设置生命"
#define str_Settings_SetAvatar_Tips1 @"亲，请选择更新头像的方式！"
#define str_Settings_SetAvatar_Tips2 @"亲，请选择头像！"
#define str_Settings_SetAvatar_Camera @"拍照"
#define str_Settings_SetAvatar_Album @"从相册选择"
#define str_Settings_LogIn @"登录"
#define str_Settings_LogOut @"注销登录"
#define str_Settings_LogOut_Success @"注销成功"
#define str_Settings_LogOut_Fail @"注销失败"
#define str_Settings_ChangePassword @"修改密码："
#define str_Settings_AutoSync @"自动同步："
#define str_Settings_Gesture @"手势解锁："
#define str_Settings_ShowGesture @"显示手势："
#define str_Settings_ChangeGesture @"修改手势："
#define str_Settings_Tips1 @"手势密码设置成功"

#define str_Register_Tips1 @"邮箱地址Email"
#define str_Register_Tips2 @"请输入邮箱地址"
#define str_Register_Tips3 @"邮箱地址格式不正确"
#define str_Register_Tips4 @"请输入密码"
#define str_Register_Tips5 @"该邮箱账号已经注册，如果密码丢失，可通过“忘记密码”找回"
#define str_Register_Tips6 @"我们给你的邮箱发了一封验证邮件，请先验证邮件后再登录使用"
#define str_Register_Tips7 @"密码Password"
#define str_Register_Tips8 @"温馨提示：注册邮箱需要接收系统的验证邮件，请填写真实有效的邮箱地址。"

#define str_LogIn_Tips1 @"账号或密码不正确"
#define str_LogIn_Tips2 @"你的账号邮箱还没通过验证，请先登录账号邮箱查看验证邮件"

#define str_ForgotPassword_Tips1 @"找回密码"
#define str_ForgotPassword_Tips2 @"我们给你的邮箱发了一封重置密码的邮件，请注意查收"

#define str_ChangePassword_Tips1 @"请输入当前密码"
#define str_ChangePassword_Tips2 @"请输入新密码"
#define str_ChangePassword_Tips3 @"请再输入一次新密码"
#define str_ChangePassword_Tips4 @"两次新密码输入不一样"
#define str_ChangePassword_Tips5 @"修改密码成功"
#define str_ChangePassword_Tips6 @"修改密码失败"
#define str_ChangePassword_Tips7 @"使用新密码登录失败"
#define str_ChangePassword_Tips9 @"旧密码不正确"

#define str_Set_Nickname @"设置昵称"
#define str_Set_Nickname_Tips1 @"请输入昵称"
#define str_Set_Nickname_Tips2 @"昵称不能大于10个字符！"

#define str_Set_Lifespan @"设置生命"
#define str_Set_Lifespan_Tips1 @"请输入生命"
#define str_Set_Lifespan_Tips2 @"请输入假如你可以活到的岁数"
#define str_Set_Lifespan_Tips3 @"别闹，请填写正常人的寿命！"

#define str_Notify_Tips1 @"提醒："
#define str_Notify_Tips2 @"你已经5天没有新建计划了，要坚持哦~"

#define str_About_Version @"当前版本："
#define str_About_Copyright @"©2015-2016 Andwho Inc."
#define str_About_Name @"MyPlan"

#define str_Share_Success @"分享成功"
#define str_Share_Fail @"分享失败"
#define str_Share_Cancel @"取消分享"
#define str_Share_URL @"http://myplan.bmob.cn/"
#define str_Share_Tips1 @"来自我有计划iOS版"
#define str_Share_Tips2 @"晒数据"
#define str_Share_Tips3 @"做计划管时间的好APP：我有计划"

#define str_Messages_Tips1 @"暂无系统消息"
#define str_Messages_Tips2 @"已读信息清理完毕"
#define str_Messages_Tips3 @"查看更多详情>>>"

#define str_CheckIn_Tips1 @"签到"
#define str_CheckIn_Tips2 @"已签到"

#define str_Sync_Begin @"正在同步数据..."
#define str_Sync_End @"同步数据完成"

#define str_Tmp_Flag @"kTmpFlag"
#define str_PostsList_UpdatedTime @"kPostsListLastLoadDataTime"
#define str_TableName_Settings @"t_settings"
#define str_TableName_Plan @"t_plan"
#define str_TableName_Photo @"t_photo"
#define str_TableName_Statistics @"t_statistics"
#define str_TableName_Task @"t_task"
#define str_TableName_TaskRecord @"t_taskrecord"
#define str_TableName_Messages @"t_messages"
#define str_Website_URL @"http://myplan.bmob.cn/"
#define str_Feedback_Email @"fengziyi@andwho.com"

#define str_DateFormatter_yyyy_MM_dd_HHmmss @"yyyy-MM-dd HH:mm:ss"
#define str_DateFormatter_yyyyMMddHHmmss @"yyyyMMddHHmmss"
#define str_DateFormatter_yyyy_MM_dd_HHmm @"yyyy-MM-dd HH:mm"
#define str_DateFormatter_yyyy_MM_dd @"yyyy-MM-dd"

#define str_Bmob_ApplicationID @"c2d17819bc025e90e998210ee07d5b4c"
#define str_SinaWeibo_AppKey @"2763375435"
#define str_SinaWeibo_AppSecret @"c0f52655316236b558b22f6b90e2ba44"
#define str_SinaWeibo_RedirectURI @"http://www.fengziyi.com"
#define str_QQ_AppID @"1104843747"
#define str_QQ_AppKey @"nq3oLSHFZa1UuzVY"
#define str_Wechat_AppKey @"wx6bae95e549a33fb8"
#define str_Wechat_AppSecret @"24dd0aaa317888920cd690ed55a98520"
#define str_ShareSDK_AppKey @"a47e7a940fac"

#endif
