//
//  StringMacro.h
//  plan
//
//  Created by Fengzy on 15/8/28.
//  Copyright (c) 2015年 Fengzy. All rights reserved.
//

#ifndef plan_StringMacro_h
#define plan_StringMacro_h

#define str_App_Title @"我有计划"

#define str_Common_Tips1 @"请到“设置”-“隐私”-“照片”中找到”我有计划“，将按钮打开，允许访问相册"
#define str_Common_Tips2 @"请到“设置”-“隐私”-“相机”中找到”我有计划“，将按钮打开，允许使用摄像头"

#define str_ViewTitle_1 @"我的"
#define str_ViewTitle_2 @"计划"
#define str_ViewTitle_3 @"任务"
#define str_ViewTitle_4 @"个人中心"
#define str_ViewTitle_5 @"岁月影像"
#define str_ViewTitle_6 @"常见问题"
#define str_ViewTitle_7 @"五星鼓励"
#define str_ViewTitle_8 @"建议反馈"
#define str_ViewTitle_9 @"关于我们"
#define str_ViewTitle_10 @"注册账号"
#define str_ViewTitle_11 @"找回密码"
#define str_NickName @"昵称"
#define str_FirstView_1 @"假如你可以活到"
#define str_FirstView_2 @"岁"
#define str_FirstView_3 @"你仅剩"
#define str_FirstView_4 @"天"
#define str_FirstView_5 @"你的今天仅剩"
#define str_FirstView_6 @"秒"
#define str_FirstView_7 @"计划总数"
#define str_FirstView_8 @"已完成数"
#define str_FirstView_9 @"完成比例"
#define str_FirstView_10 @"类型"
#define str_FirstView_11 @"每日计划"
#define str_FirstView_12 @"长远计划"

#define str_Save_Success @"保存成功"
#define str_Save_Fail @"保存失败"
#define str_Delete_Success @"删除成功"
#define str_Delete_Fail @"删除失败"
#define str_OK @"确定"
#define str_Cancel @"取消"
#define str_Show @"显示"
#define str_Notify_Later @"稍后提醒"
#define str_Delete_Plan @"删除该计划"
#define str_NoPlan_EveryDay @"暂无每日计划内容"
#define str_NoPlan_LongTerm @"暂无长远计划内容"
#define str_Alert_GetIt @"确定"
#define str_Plan_Add @"新增计划"
#define str_Plan_Edit @"编辑计划"
#define str_Plan_NoContent @"至少写点什么吧"
#define str_Plan_Today @"今天"
#define str_Plan_Yesterday @"昨天"

#define str_Photo_Add @"新增影像"
#define str_Photo_Edit @"编辑影像"
#define str_Photo_Add_Tips1 @"写点什么..."
#define str_Photo_Add_Tips2 @"请选择添加照片的方式"
#define str_Photo_Add_Tips3 @"请选择照片"
#define str_Photo_Add_Tips4 @"可选9张照片"
#define str_Photo_Add_Tips5 @"至少留一张照片吧~"
#define str_Photo_Add_Tips6 @"已选%ld张/还可选%ld张照片"
#define str_Photo_Add_Tips7 @"拍照地点"
#define str_Photo_Tips1 @"暂无影像内容"
#define str_Photo_Detail @"影像详情"
#define str_Photo_Age @"岁"
#define str_Photo_Location @"地点："
#define str_Photo_Date @"时间："
#define str_Photo_Detail_Tips1 @"时间：%@"
#define str_Photo_Detail_Tips2 @"%@   地点：%@"
#define str_Photo_Delete_Tips @"删除该影像"

#define str_Task_Tips1 @"暂无任务内容"

#define str_More @"更多"
#define str_More_Settings @"通用设置"
#define str_More_Welcome @"去欢迎页"

#define str_More_Feedback_Tips1 @"当前系统版本不支持应用内发送邮件功能"
#define str_More_Feedback_Tips2 @"你还没有设置邮件账户"
#define str_More_Feedback_Tips3 @"请输入你的建议或反馈~"
#define str_More_Feedback_Tips4 @"取消编辑邮件"
#define str_More_Feedback_Tips5 @"保存邮件成功"
#define str_More_Feedback_Tips6 @"发送邮件成功"
#define str_More_Feedback_Tips7 @"保存或者发送邮件失败"
#define str_More_Feedback_Tips8 @"我有计划 For iOS"

#define str_Settings_Avatar @"头像："
#define str_Settings_Nickname @"昵称："
#define str_Settings_Nickname_Tips @"点击修改昵称"
#define str_Settings_Gender @"性别："
#define str_Settings_Gender_M @" 男"
#define str_Settings_Gender_F @" 女"
#define str_Settings_Birthday @"生日："
#define str_Settings_Birthday_Tips @"点击设置生日"
#define str_Settings_Lifespan @"生命："
#define str_Settings_Lifespan_Tips @"点击设置生命"
#define str_Settings_SetAvatar_Tips1 @"亲，请选择更新头像的方式！"
#define str_Settings_SetAvatar_Tips2 @"亲，请选择头像！"
#define str_Settings_SetAvatar_Camera @"拍照"
#define str_Settings_SetAvatar_Album @"从相册选择"
#define str_Settings_LogIn @"登录or注册"
#define str_Settings_LogIn_QQ_Tips1 @"没有安装QQ客户端"
#define str_Settings_LogIn_SinaWeibo_Tips1 @"没有安装微博客户端"
#define str_Settings_LogOut @"注销登录"
#define str_Settings_LogOut_Success @"注销成功"
#define str_Settings_LogOut_Fail @"注销失败"

#define str_Set_Nickname @"设置昵称"
#define str_Set_Nickname_Tips1 @"请输入昵称"
#define str_Set_Nickname_Tips2 @"昵称不能大于10个字符！"

#define str_Set_Lifespan @"设置生命"
#define str_Set_Lifespan_Tips1 @"请输入生命"
#define str_Set_Lifespan_Tips2 @"请输入假如你可以活到的岁数"
#define str_Set_Lifespan_Tips3 @"别闹，请填写正常人的寿命！"

#define str_Notify_Tips1 @"提醒："
#define str_Notify_Tips2 @"你已经5天没有新建计划了，要坚持哦~"

#define str_About_Version @"当前版本："
#define str_About_Copyright @"© 2015 Andwho Inc."
#define str_About_Name @"MyPlan"
#define str_About_Content @"对于世界上大多数人，生命的长度最多不过30000来天。所以，时间对于每一个人都是奢侈品。人生苦短，时间有限，想要成功就得对自己狠一点，从坚持每天给自己定一些计划开始，然后逐个完成它们，让生活更有意义，让生命更有价值。乔布斯说过：活着就是为了改变世界！就算不能改变世界，理想还是要有的，只要坚持不懈，万一哪天就实现了呢？"

#define str_Share_Success @"分享成功"
#define str_Share_Fail @"分享失败"
#define str_Share_Cancel @"取消分享"
#define str_Share_Content @"推荐一个好玩的应用，你也安装试试啊~可惜目前只有iOS版ToT"
#define str_Share_URL @"http://www.fengziyi.com/andwho-plan/"

#define str_Avatar @"kAvatar"
#define str_LogInPlatform @"kLogInPlatform"
#define str_TableName_Settings @"t_settings"
#define str_TableName_Plan @"t_plan"
#define str_TableName_Photo @"t_photo"
#define str_TableName_Statistics @"t_statistics"
#define str_TableName_Task @"t_task"
#define str_TableName_TaskRecord @"t_taskrecord"
#define str_Website_URL @"http://www.fengziyi.com"
#define str_Feedback_Email @"fengziyi@andwho.com"

#define str_DateFormatter_yyyy_MM_dd_HHmmss @"yyyy-MM-dd HH:mm:ss"
#define str_DateFormatter_yyyyMMddHHmmss @"yyyyMMddHHmmss"
#define str_DateFormatter_yyyy_MM_dd_HHmm @"yyyy-MM-dd HH:mm"
#define str_DateFormatter_yyyy_MM_dd @"yyyy-MM-dd"

#define str_Bmob_ApplicationID @"ed10fc9a05fd6fd5c37be211bc0726b2"
#define str_SinaWeibo_AppKey @"2763375435"
#define str_SinaWeibo_AppSecret @"c0f52655316236b558b22f6b90e2ba44"
#define str_SinaWeibo_RedirectURI @"http://www.fengziyi.com"
#define str_QQ_AppID @"1104873268"
#define str_QQ_AppKey @"0HK3NGbEdP1sCMmr"
#define str_Wechat_AppKey @"wx6bae95e549a33fb8"
#define str_Wechat_AppSecret @"24dd0aaa317888920cd690ed55a98520"
#define str_ShareSDK_AppKey @"a47e7a940fac"

#endif
